# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d7a339f70331b250a627463790dbde759166f4ff2468135a64b30ede91f74735fcf480fdbc8c083b183b3080fecd51bfd5824037431d283464462153a99f629

test:
  secret_key_base: b6c0d96f9a67d7a28d3ee0ad1ac7900691b32d0a8a3e6fbd9f96702a1c7b90312e880d168fb0df4ea7f361c7263d767d2e493c7f19f7dac1aa3d12e719330d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
